# Transposição e Reshaping

In [3]:
import numpy as np

In [4]:
A = np.array([[10,20,30],[40,50,60]])

A

array([[10, 20, 30],
       [40, 50, 60]])

In [5]:
A.T

array([[10, 40],
       [20, 50],
       [30, 60]])

In [6]:
np.transpose(A)

array([[10, 40],
       [20, 50],
       [30, 60]])

# Broadcast

In [7]:
B = np.array([[100,200,300]])

In [8]:
B.T

array([[100],
       [200],
       [300]])

In [9]:
B.T + B

array([[200, 300, 400],
       [300, 400, 500],
       [400, 500, 600]])

# Convertendo Matrizes em Arrays

In [10]:
A = np.array([np.arange(10,60,10), np.arange(100,150,10)])

A

array([[ 10,  20,  30,  40,  50],
       [100, 110, 120, 130, 140]])

In [11]:
A.shape

(2, 5)

In [12]:
A.ravel()

array([ 10,  20,  30,  40,  50, 100, 110, 120, 130, 140])

In [13]:
A.T.ravel()

array([ 10, 100,  20, 110,  30, 120,  40, 130,  50, 140])

# Operadores lógicos

In [15]:
array = np.random.randint(1, 10, size =(4,4))

array

array([[7, 1, 5, 3],
       [4, 3, 8, 6],
       [1, 2, 2, 8],
       [2, 9, 2, 1]])

In [16]:
# operador lógico "any" se qualquer elemento atender a condição o resultado é True

np.any((array % 7) == 0)

True

In [17]:
# operador lógico "all" todos elementos devem atender a condição para o resultado ser True

np.all(array < 11)

True

# Reshaping

In [18]:
array = np.arange(1,16)

array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
array.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

# Ordenando Arrays

In [20]:
array = np.array([[3,2],[10,-1]])

array

array([[ 3,  2],
       [10, -1]])

In [23]:
# Ordenando por linhas
array.sort(axis = 1)

array

array([[ 2,  3],
       [-1, 10]])

In [24]:
array = np.array([[3,2],[10,-1]])

array

array([[ 3,  2],
       [10, -1]])

In [26]:
# Ordenando por colunas

array.sort(axis = 0)

array

array([[ 3, -1],
       [10,  2]])