In [1]:
# importando a biblioteca

import numpy as np
import pandas as pd

In [2]:
# Estruturas unidimensionais

a1 = np.array(['Spark', 'Hadoop','Python', 'R'])

a1

array(['Spark', 'Hadoop', 'Python', 'R'], dtype='<U6')

In [5]:
# Estruturas bidimensionais

a2 = np.array([['Altura','Largura','Profundidade'],[42, 78, 10]])

a2

array([['Altura', 'Largura', 'Profundidade'],
       ['42', '78', '10']], dtype='<U12')

In [6]:
a3 = np.array([[10,20,30],[40,50,60]])

a3

array([[10, 20, 30],
       [40, 50, 60]])

In [7]:
# Tamanho do array


print(a1.shape)
print(a2.shape)


(4,)
(2, 3)


In [10]:
# Dimensões do Array

a1.ndim

1

In [11]:
a2.ndim

2

In [12]:
# Valor máximo

a3.max()

60

In [13]:
a2.ndim

2

In [15]:
# Metodo Arange

array = np.arange(20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
# Usando start/end - de 0 a 100 em 10

array = np.arange(0, 100, 10)

array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Criando estruturas de dados com o linspace
# no linspace o ultimo elemento é o número de elementos do vetor

In [19]:
matriz = np.linspace(0,10,20)

matriz

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [20]:
matriz = np.linspace(0, 10, 5)

matriz

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
matriz = np.linspace(0, 5, 5)

matriz

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [22]:
#Estrutura de Matrizes

# numpy.zeros

matriz = np.zeros((10, 10))

matriz

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
# numpy.ones, cria matrizes com o número 1

matriz = np.ones((2, 3))

matriz

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
# numpy.eye, cria matrizes do tipo identidade

matriz = np.eye(10)

matriz

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [25]:
# numpy.diag produz o mesmo resultado, porem, podemos definir os números diagonais

matriz = np.diag((2, 4, 6, 8, 10, 12, 14, 16, 18, 20))

matriz

array([[ 2,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  6,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  8,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 10,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 12,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 14,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 16,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 18,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 20]])

In [27]:
# numpy.empty produz uma matriz vazia

matriz = np.empty((10,5))

matriz

array([[             nan,  1.33360289e+241,  5.47424736e-321,
         4.94065646e-324,  5.67187361e-321],
       [ 2.66749140e-296,  5.69163624e-321,  3.22925319e-310,
         4.58492919e-321,  1.27319748e-312],
       [ 5.77068674e-321,  2.43896182e-260,  3.93276254e-321,
         3.12056457e-309,  6.77858066e-321],
       [ 1.63409463e+069,  6.52166653e-321,  1.54725422e+272,
         6.87739379e-321,  4.61268380e-303],
       [ 6.81810591e-321,  6.17500775e-312,  6.89715642e-321,
         1.33360289e+241,  6.79834329e-321],
       [ 1.17337634e-275,  3.02160049e-287,  1.15549302e-313,
         1.03539814e-308,  1.33360293e+241],
       [ 5.67421675e-311,  1.00562508e-248,  8.26401314e-312,
         2.71406007e+243,  2.25733854e+161],
       [ 3.67127367e+228,  7.30476670e-311,  3.63142389e-249,
         3.11490785e+150,  8.39132778e-311],
       [-5.45150448e-268,  5.04264471e+223,  1.17122415e+166,
         6.43669542e+247,  5.89016874e+231],
       [ 3.57200998e+252,  2.56535590

In [28]:
# numpy.tile

np.tile(np.array([[1,2],[3,4],[5,6]]), 3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6]])

In [29]:
np.tile(np.array([[1,2],[3,4],[5,6]]),(3,6))

array([[1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6]])