In [3]:
# Importação do Numpy

import numpy as np

# Tipagem de dados

In [2]:
# Tipando um array por parêmetro

a = np.array([-10, 10, 20, 30], dtype = 'float')

a

array([-10.,  10.,  20.,  30.])

In [3]:
a.dtype

dtype('float64')

In [5]:
b = np.array([-10, 10, 20, 30])

b.dtype

dtype('int32')

In [6]:
c = np.array([-10, 10, 20, 30, 40.5])

c.dtype

dtype('float64')

In [7]:
# Tipo string

d = np.array(['Universidade', 'dos', 'Dados'])

d.dtype

dtype('<U12')

In [8]:
#Array tipo boleano

e = np.array([False, False, True])

e.dtype

dtype('bool')

# Cast de Arrays

In [9]:
# Transformação de tipos

f = np.array([-9, 10, 20.7])

f.dtype

dtype('float64')

In [10]:
# Posso realizar CAST com a função astype()

f.astype(int)

array([-9, 10, 20])

# Criando Arrays com operações aritiméticas em tempo de execução

In [12]:
# Aprendemos que a função arange serve para criar um array

array = np.arange(0,5)

array

array([0, 1, 2, 3, 4])

In [13]:
# Podemos criar um array com qualquer operação aritimética

array = np.arange(0,10) ** 2

array

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

# Operações entre Arrays

In [14]:
arrayA = np.arange(0,10)
arrayB = np.arange(0,10)+1

In [15]:
arrayA

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arrayB

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
# Soma

arrayA + arrayB

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [19]:
# Subtração

arrayA - arrayB

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [20]:
# Divisão

arrayA / arrayB

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ,
       0.83333333, 0.85714286, 0.875     , 0.88888889, 0.9       ])

In [21]:
# Multiplicação

arrayA * arrayB

array([ 0,  2,  6, 12, 20, 30, 42, 56, 72, 90])

In [22]:
# Comparações

arrayA == arrayB

array([False, False, False, False, False, False, False, False, False,
       False])

In [23]:
arrayA > arrayB

array([False, False, False, False, False, False, False, False, False,
       False])

In [24]:
arrayA < arrayB

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
# Podemos trabalhar com tabela verdade para comparar dois arrays

In [28]:
array1 = np.array([True,False,True,False])
array2 = np.array([False, False,True,False])
np.logical_and(array1, array2)

array([False, False,  True, False])

In [30]:
array1 = np.array([True,False,True,False])
array2 = np.array([False, False,True,False])
np.logical_or(array1, array2)

array([ True, False,  True, False])

# Arrays com tamanhos diferentes

In [4]:
A = np.array([1,2,3,4,5])
B = np.array([1,2,3])

In [5]:
A + B # Não calcula

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [6]:
A * B # Não calcula

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

# Dot product

In [8]:
A = np.array([2,4,6])
B = np.array([2,2,2])

In [9]:
# Hadmard Product

A * B

array([ 4,  8, 12])

In [10]:
# Dot Product

print(np.dot(A,B))

24


In [12]:
A = np.array([3,7,10])
B = np.array([9,3,2])

In [13]:
A * B

array([27, 21, 20])

In [14]:
print(np.dot(A,B))

68


# Cópia de Arrays

In [17]:
# Erro na maneira de copiar arrays

A = np.arange(10)

A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
B = A[5:]

B

array([5, 6, 7, 8, 9])

In [20]:
A[:] = 0

B

array([0, 0, 0, 0, 0])

In [21]:
# Maneira correta de se fazer a cópia de um array

A = np.arange(10)

A

B = A[5:].copy()

B

array([5, 6, 7, 8, 9])