In [1]:
import numpy as np

In [2]:
a = [1,2,11,6,8,18,2]

array = np.array(a)

print(type(array))

<class 'numpy.ndarray'>


In [4]:
# verificando tamanho da array unidimensional

print(array.shape)

(7,)


In [5]:
#primeiro elemento

array[0]

1

In [6]:
# elemento no indice 2

array[2]

11

In [7]:
# ultimo elemento

array[-1]

2

In [8]:
# do primeiro até o quinto elemento

array[0:5]

array([ 1,  2, 11,  6,  8])

In [9]:
# utilizando saltos(passos) no array

array[1:5:2]

array([2, 6])

In [10]:
# utilizando indices negativos
# -7 representa o primeiro item a esquerda e -3 o ultimo elemento a ser pego 

print(array[-7:-3])

[ 1  2 11  6]


In [11]:
# indice 3 até o final

array[3:]

array([ 6,  8, 18,  2])

In [12]:
# do inicio até o indice 4

array[:4]

array([ 1,  2, 11,  6])

In [13]:
#invertendo o array

array[::-1]

array([ 2, 18,  8,  6, 11,  2,  1])

In [14]:
# copiando um array por referência

b = array[:]
print(b)

[ 1  2 11  6  8 18  2]


In [16]:
#concatenar dois array ou mais

x = np.array([2,6,8,4])

y = np.array([11,8,2])

z = np.concatenate([x,y])

print(z)

[ 2  6  8  4 11  8  2]
