In [1]:
import numpy as np

In [11]:
A = [[1,2,3,4],[5,6,7,8],[10,20,30,40],[50,60,70,80]]

array = np.array(A)

print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 20 30 40]
 [50 60 70 80]]


In [5]:
# primeira linha

print(array[0])

[1 2 3 4]


In [6]:
# linha indice 2

print(array[2])

[10 20 30 40]


In [7]:
# Primeira linha e ultima coluna

print(array[0,-1])

4


In [15]:
# Atribuindo valor a uma posição na matriz

print(array)

array[0,0] = 0

print(array)

[[ 0  2  3  4]
 [ 5  6  7  8]
 [10 20 30 40]
 [50 60 70 80]]
[[ 0  2  3  4]
 [ 5  6  7  8]
 [10 20 30 40]
 [50 60 70 80]]


# Trabalhando com intervalos

In [17]:
# Pegando os numeros centrais

print(array[1:3,1:3])

[[ 6  7]
 [20 30]]


In [18]:
# Pegando o intervalo 7,8,30,40

print(array[1:3,2:4])

[[ 7  8]
 [30 40]]


In [29]:
# Pegar somente a ultima coluna

print(array[:,-1])

[ 4  8 40 80]


In [30]:
# Pegar somente a última linha 

print(array[-1:])

[[50 60 70 80]]


In [31]:
# Concatenar multidimensionais

A = np.array([[1,2],[3,4]])

B = np.array([[5,6]])

C = np.concatenate([A,B])

print(C)

[[1 2]
 [3 4]
 [5 6]]
