In [1]:
import numpy as np

In [5]:
A = np.matrix([[1,2],[3,4]])

B = np.matrix([[5,3],[8,7]])

Z = np.array([
    [[2,6],[8,4]],
    [[2,6],[8,4]],
    [[2,6],[8,4]]
])

Y = np.array([2,6,8,4])

In [6]:
Z = np.matrix([
    [[2,6],[8,4]],
    [[2,6],[8,4]],
    [[2,6],[8,4]]
])

ValueError: matrix must be 2-dimensional

In [3]:
print(type(A))

<class 'numpy.matrix'>


In [7]:
print(type(Z))

<class 'numpy.ndarray'>


In [8]:
print(type(Y))

<class 'numpy.ndarray'>


In [9]:
print(A)

[[1 2]
 [3 4]]


In [10]:
print(Z)

[[[2 6]
  [8 4]]

 [[2 6]
  [8 4]]

 [[2 6]
  [8 4]]]


In [11]:
print(Y)

[2 6 8 4]


In [12]:
Z.shape

(3, 2, 2)

In [13]:
Y.shape

(4,)

In [14]:
A.shape

(2, 2)

In [15]:
B.shape

(2, 2)

# Soma

In [16]:
print(A + B)

[[ 6  5]
 [11 11]]


In [17]:
print(B + 3)

[[ 8  6]
 [11 10]]


# Subtração

In [18]:
print(A - B)

[[-4 -1]
 [-5 -3]]


# Multiplicação

In [19]:
A = np.matrix([[1,2],[3,4]])

print(A)

[[1 2]
 [3 4]]


In [20]:
# Arrumação em Cruz

print(A * A)

[[ 7 10]
 [15 22]]


In [21]:
# Multiplicação indice a indice

print(np.multiply(A,A))

[[ 1  4]
 [ 9 16]]


# Inversa

In [22]:
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [23]:
from numpy.linalg import inv

In [24]:
print(inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


# Transposta

In [25]:
print(A.T)

[[1 3]
 [2 4]]
